// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

/* interface CloudflareEnv {
} */

export type Type_responseListActive = {
    id?: number | null;
    cdAluno?: string | null;
    nrAno?: number | null;
    nrSemestre?: number | null;
    nmQuestionario?: string | null;
    cdDisciplina?: string | null;
    nmDisciplina?: string | null;
    dsSitDetalhe?: string | null;
    idQuestionario?: number | null;
    dhInicioSolicitacao?: number | null;
    dhFimSolicitacao?: number | null;
    dhInicioRealizacao?: number | null;
    dhFimRealizacao?: number | null;
    dsTipoOportunidade?: string | null;
    idQuestionarioAluno?: number | null;
    dtAvaliacao?: string | null;
    dhLocal?: string | null;
    hrInicial?: string | null;
    hrFinal?: string | null;
    idPolo?: number | null;
    nmPolo?: string | null;
    flAgendado?: boolean | null;
    flPodeAgendar?: boolean | null;
    flPodeCancelarAgendamento?: boolean | null;
    flPodeIniciar?: boolean | null;
    flUtilizaCredito?: boolean | null;
    flPodeResponder?: boolean | null;
    nrCredito?: number | null;
    dsStatus?: string | null;
    idPoloAluno?: number | null;
    nmPoloAluno?: string | null;
    flTransicao?: boolean | null;
    nrTempoTolerancia?: number | null;
    flTempoExcedido?: boolean | null;
    flProvaExtra?: boolean | null;
    dtInicioSolicitacaoStr?: string | null;
    dtFimSolicitacaoStr?: string | null;
    dtInicioRealizacaoStr?: string | null;
    dtFimRealizacaoStr?: string | null;
    vlPercentualRespondido?: number | null;
    flLiberado?: boolean | null;
}[];

export type Type_responseListClosed = {
    id?: number | null;
    cdAluno?: string | null;
    nrAno?: number | null;
    nrSemestre?: number | null;
    nmQuestionario?: string | null;
    cdDisciplina?: string | null;
    nmDisciplina?: string | null;
    dsSitDetalhe?: string | null;
    idQuestionario?: number | null;
    dhInicioSolicitacao?: number | null;
    dhFimSolicitacao?: number | null;
    dhInicioRealizacao?: number | null;
    dhFimRealizacao?: number | null;
    dsTipoOportunidade?: string | null;
    idQuestionarioAluno?: number | null;
    dtAvaliacao?: string | null;
    dhLocal?: number | null;
    hrInicial?: string | null;
    hrFinal?: string | null;
    idPolo?: number | null;
    nmPolo?: string | null;
    flAgendado?: boolean | null;
    flPodeAgendar?: boolean | null;
    flPodeCancelarAgendamento?: boolean | null;
    flPodeIniciar?: boolean | null;
    flUtilizaCredito?: boolean | null;
    nrCredito?: number | null;
    dsStatus?: string | null;
    nrTempoTolerancia?: number | null;
    flCopiaProva?: boolean | null;
    vlPercentualRespondido?: number | null;
}[];

export type Type_responseListCanceled = {
    id?: number | null;
    cdAluno?: string | null;
    nrAno?: number | null;
    nrSemestre?: number | null;
    nmQuestionario?: string | null;
    cdDisciplina?: string | null;
    nmDisciplina?: string | null;
    dsSitDetalhe?: string | null;
    idQuestionario?: number | null;
    dhInicioSolicitacao?: number | null;
    dhFimSolicitacao?: number | null;
    dhInicioRealizacao?: number | null;
    dhFimRealizacao?: number | null;
    dsTipoOportunidade?: string | null;
    idQuestionarioAluno?: number | null;
    dtAvaliacao?: string | null;
    dhLocal?: number | null;
    hrInicial?: string | null;
    hrFinal?: string | null;
    idPolo?: number | null;
    nmPolo?: string | null;
    flAgendado?: boolean | null;
    flPodeAgendar?: boolean | null;
    flPodeCancelarAgendamento?: boolean | null;
    flPodeIniciar?: boolean | null;
    flUtilizaCredito?: boolean | null;
    nrCredito?: number | null;
    dsStatus?: string | null;
    nrTempoTolerancia?: number | null;
    dhCancelado?: number | null;
    dhInsert?: number | null;
}[];

export type Type_responseListExamFullOnline = {
    idQuestionarioAluno: number;
    nmAluno: string;
    cdAluno: string;
    nmCurso: string;
    cdDisciplina: string;
    nmQuestionario: string;
    dsOrigemAgendamento: string;
    dsTipoOportunidade: string;
    flLiberado: boolean;
    flPodeLiberar: boolean;
    nrPercentual: number;
    cdPoloMundoAzul: number;
    idHorario: number;
    nmPolo: string;
    nrTempoExtra: string;
    flTempoExtra: boolean;
    idOcorrencia: number | null;
    dsTipoProva: string;
    nrAno: number;
    nrModulo: number;
    cdUnidadeEnsino: string;
    nmUnidadeEnsino: string;
    dsEmail: string | null;
    dtAvaliacao: string;
    cdCpf: string;
    cdCurso?: string;
    hrInicial?: string;
    hrFinal?: string;
};

export type Type_allModifiedList = Type_responseListExamFullOnline & {
    pricing: number;
    acquired: boolean;
    status: string;
    jwtInf: string;
};

export type Type_backendStudent = {
    student_uuid: string;
    college_uuid_student: string | null;
    course_uuid_student: string | null;
    is_suggested_information_student: 0 | 1;
};

export type Type_backendCollege = {
    college_uuid: string;
    name_college: string;
    svg_college: string | null;
};

export type Type_backendCourse = {
    course_uuid: string;
    name_course: string;
    svg_course: string | null;
    college_uuid_course: string;
};

export type Type_backendContent = {
    content_uuid: string;
    content_update: string;
    name_content: string;
    student_uuid_content: string;
    old_price_content: number | null;
    current_price_content: number;
    preview_file_uuid_content: string | null;
    full_file_uuid_content: string | null;
    college_uuid_content: string;
    course_uuid_content: string;
    prevision_content: string | null;
    verified_content: 0 | 1;
};

export type Type_backendContentBiblioteca = Type_backendContent & {
    isAcquiredContent: boolean;
};

export type Type_backendStudentLoginResponse = {
    student: Type_backendStudent;
    collegeArray: Type_backendCollege[];
    courseArray: Type_backendCourse[];
    contentArray: Type_backendContentBiblioteca[];
    cartArray: Type_backendContent[];
};

export type Type_backendStudentBibliotecaResponse = {
    contentArray: Type_backendContentBiblioteca[];
};

export type Type_backendStudentPostadoResponse = {
    contentArray: Type_backendContent[];
};

export type Type_backendStudentConteudoResponse = {
    content: Type_backendContent;
};

export type Type_backendStudentConteudoFileResponse = {
    content: Type_backendContent;
    fileRole: 'preview' | 'full';
    fileUuidContent: string;
};

export type Type_backendStudentPixPaymentResponse = {
    pixCopiaECola: string;
    contentUuidArray: Array<string>;
};

export type Type_backendAdminConfigWebhookEfiResponse = {
    success: true;
    pixCopiaECola: string;
};
